package main

import (
	"testing"
)

func TestConvert(t *testing.T) {
	tcs := []struct {
		inStr  string
		inRows int
		outStr string
	}{
		{"PAYPALISHIRING", 3, "PAHNAPLSIIGYIR"},
		{"PAYPALISHIRING", 4, "PINALSIGYAHRPI"},

		{"", 4, ""},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", -1, "ABCDEFGHIJKLNMOPQRSTUVWXYZ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 0, "ABCDEFGHIJKLNMOPQRSTUVWXYZ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 1, "ABCDEFGHIJKLNMOPQRSTUVWXYZ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 2, "ACEGIKNOQSUWYBDFHJLMPRTVXZ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 3, "AEINQUYBDFHJLMPRTVXZCGKOSW"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 4, "AGNSYBFHLMRTXZCEIKOQUWDJPV"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 5, "AIQYBHJPRXZCGKOSWDFLMTVENU"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 6, "AKUBJLTVCINSWDHMRXEGOQYFPZ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 7, "ANYBLMXZCKOWDJPVEIQUFHRTGS"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 8, "AOBMPCNQDLRZEKSYFJTXGIUWHV"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 9, "AQBPRCOSDMTENUFLVGKWHJXZIY"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 10, "ASBRTCQUDPVEOWFMXGNYHLZIKJ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 15, "ABCDZEYFXGWHVIUJTKSLRNQMPO"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 20, "ABCDEFGHIJKLNMZOYPXQWRVSUT"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 26, "ABCDEFGHIJKLNMOPQRSTUVWXYZ"},
		{"ABCDEFGHIJKLNMOPQRSTUVWXYZ", 50, "ABCDEFGHIJKLNMOPQRSTUVWXYZ"},
	}

	for idx, tc := range tcs {
		out := convert(tc.inStr, tc.inRows)
		if out != tc.outStr {
			t.Errorf("%d. convert(%q, %d) = %q. Expected: %q", idx, tc.inStr, tc.inRows, out, tc.outStr)
		}
	}
}
